#//This file is the configuration file for the XCPC_board project
storages:
  mysql:
    host: mysql:3306
    username: root
    password: mysql114514
  redis:
    host: redis:6379
    password: 123456